# Generated by Django 3.0.8 on 2020-07-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Editions_Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript_Editions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bold', models.CharField(blank=True, max_length=250)),
                ('name_date', models.CharField(blank=True, max_length=250)),
                ('name_original', models.CharField(blank=True, max_length=250)),
                ('name_latin', models.CharField(blank=True, max_length=250)),
                ('personalia', models.TextField(blank=True, max_length=500)),
                ('literature', models.TextField(blank=True, max_length=1500)),
                ('literature_editions', models.TextField(blank=True, max_length=1500)),
                ('vitea', models.TextField(blank=True, max_length=500)),
                ('vitea_bigiographies', models.TextField(blank=True, max_length=500)),
                ('works_editions', models.TextField(blank=True, max_length=500)),
                ('editions_music', models.TextField(blank=True, max_length=500)),
                ('surviving_works', models.TextField(blank=True, max_length=500)),
                ('edities_studies', models.TextField(blank=True, max_length=1500)),
                ('manuscripts_editions_literature', models.TextField(blank=True, max_length=1500)),
                ('salimbenes_literary_legacy', models.TextField(blank=True, max_length=1500)),
                ('studies', models.TextField(blank=True, max_length=1500)),
                ('primo_vita_bona', models.TextField(blank=True, max_length=500)),
                ('letter', models.CharField(blank=True, max_length=1)),
                ('editions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Editions')),
                ('editions_translations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Editions_Translations')),
                ('manuscripts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Manuscript')),
                ('manuscripts_editions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Manuscript_Editions')),
                ('translations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Translations')),
            ],
        ),
    ]
