# Generated by Django 3.0.8 on 2020-07-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0002_auto_20200724_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editions',
            new_name='Edition',
        ),
    ]
