# Generated by Django 3.0.8 on 2020-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0003_auto_20200724_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='vitea_bigiographies',
            new_name='vitea_biographies',
        ),
    ]
