# Generated by Django 3.0.8 on 2020-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0005_auto_20200819_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='literature',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
