# Generated by Django 3.0.8 on 2020-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0006_auto_20200819_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
