# Generated by Django 3.0.8 on 2020-09-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0008_auto_20200819_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=250)),
                ('biography', models.CharField(blank=True, max_length=250)),
                ('birth', models.CharField(blank=True, max_length=250)),
                ('death', models.CharField(blank=True, max_length=250)),
                ('checked', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Date_precision',
            fields=[
                ('date_precision_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_precision', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('publisher', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('detaiL_descriptions', models.CharField(blank=True, max_length=250)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author')),
                ('date_precision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Date_precision')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Location_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_name', models.CharField(blank=True, max_length=250)),
                ('fr_province', models.CharField(blank=True, max_length=250)),
                ('date', models.CharField(blank=True, max_length=250)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author')),
                ('date_precision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Date_precision')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_group', models.CharField(blank=True, max_length=250)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date_precision_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_dates', to='franciscanauthors_model.Date_precision'),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date_precision_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_dates', to='franciscanauthors_model.Date_precision'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=250)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_comments', models.CharField(blank=True, max_length=250)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author')),
            ],
        ),
    ]
