# Generated by Django 3.0.8 on 2021-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0009_auto_20200928_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='detaiL_descriptions',
            new_name='detail_descriptions',
        ),
        migrations.AddField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_stub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
