# Generated by Django 3.0.8 on 2021-03-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0010_auto_20210303_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date_precision_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_dates', to='franciscanauthors_model.Date_precision'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date_precision_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_dates', to='franciscanauthors_model.Date_precision'),
        ),
    ]
