# Generated by Django 3.0.8 on 2021-03-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0012_auto_20210303_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='author_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='author_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author'),
        ),
        migrations.AlterField(
            model_name='genre_group',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Genre'),
        ),
        migrations.AlterField(
            model_name='location_time',
            name='author_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author'),
        ),
        migrations.AlterField(
            model_name='location_time',
            name='date_precision_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Date_precision'),
        ),
        migrations.AlterField(
            model_name='works',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Author'),
        ),
        migrations.AlterField(
            model_name='works',
            name='date_precision_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Date_precision'),
        ),
        migrations.AlterField(
            model_name='works',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franciscanauthors_model.Genre'),
        ),
    ]
