# Generated by Django 3.0.8 on 2021-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0013_auto_20210305_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
