# Generated by Django 3.0.8 on 2021-03-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0014_auto_20210305_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_stub',
            field=models.BooleanField(default=False),
        ),
    ]
