# Generated by Django 3.0.8 on 2021-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0015_genre_is_stub'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='text',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='add_comments',
            field=models.TextField(blank=True, max_length=200000),
        ),
    ]
