# Generated by Django 3.1.12 on 2021-06-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0016_auto_20210614_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='author_ID',
            new_name='author_id',
        ),
    ]
