# Generated by Django 3.1.12 on 2021-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0018_auto_20210614_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='add_comments',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
