# Generated by Django 3.1.12 on 2021-06-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0019_auto_20210614_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_time',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_time_list', to='franciscanauthors_model.author'),
        ),
    ]
