# Generated by Django 3.1.12 on 2021-06-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0021_auto_20210621_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_time',
            old_name='date_precision_id',
            new_name='date_precision',
        ),
    ]
