# Generated by Django 3.1.12 on 2021-06-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0022_auto_20210623_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date_precision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors_birth_date', to='franciscanauthors_model.date_precision'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date_precision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors_death_date', to='franciscanauthors_model.date_precision'),
        ),
    ]
