# Generated by Django 3.1.12 on 2021-06-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0023_auto_20210623_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_time',
            name='date_precision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_times_date_precision', to='franciscanauthors_model.date_precision'),
        ),
    ]
