# Generated by Django 3.1.12 on 2021-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0024_auto_20210623_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre_group',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre_group',
            name='genre',
            field=models.ManyToManyField(to='franciscanauthors_model.Genre'),
        ),
    ]
