# Generated by Django 3.1.12 on 2021-07-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0025_auto_20210707_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='affiliation',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
