# Generated by Django 3.1.12 on 2021-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0026_author_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_group',
            name='genre',
            field=models.ManyToManyField(related_name='genre_group_genres', to='franciscanauthors_model.Genre'),
        ),
    ]
