# Generated by Django 3.1.12 on 2021-07-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franciscanauthors_model', '0027_auto_20210721_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_comments', models.TextField(blank=True, max_length=200000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_list', to='franciscanauthors_model.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Additional_info',
        ),
    ]
